version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cooper
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    depends_on:
      - postgres
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
      DISABLE_TLS: "true"
    ports:
      - "5433:80"

volumes:
  postgres:
