export const monthOptions = [
  { value: "1", label: "January" },
  { value: "2", label: "February" },
  { value: "3", label: "March" },
  { value: "4", label: "April" },
  { value: "5", label: "May" },
  { value: "6", label: "June" },
  { value: "7", label: "July" },
  { value: "8", label: "August" },
  { value: "9", label: "September" },
  { value: "10", label: "October" },
  { value: "11", label: "November" },
  { value: "12", label: "December" },
];

// use this api to update majors: https://api.graduatenu.com/api/majors/supportedMajors
export const majors = [
  "Africana Studies and English, BA",
  "Africana Studies and Human Services, BA",
  "Africana Studies and Journalism, BA",
  "Africana Studies and Media and Screen Studies, BA",
  "Africana Studies and Political Science, BA",
  "Africana Studies, BA",
  "American Sign Language and Human Services, BS",
  "American Sign Language and Linguistics, BS",
  "American Sign Language and Psychology, BS",
  "American Sign Language and Theatre, BS",
  "American Sign Language—English Interpreting, BS",
  "Applied Physics, BS",
  "Applied Psychology, BA",
  "Architectural Studies and Design, BS",
  "Architectural Studies, BS",
  "Architecture and English, BS",
  "Architecture, BS",
  "Art, BA",
  "Behavioral Neuroscience and Design, BS",
  "Behavioral Neuroscience and Philosophy, BS",
  "Behavioral Neuroscience, BS",
  "Biochemistry, BS",
  "Bioengineering and Biochemistry, BSBioE",
  "Bioengineering, BSBioE",
  "Biology and English, BS",
  "Biology and Mathematics, BS",
  "Biology and Political Science, BS",
  "Biology, BS",
  "Biomedical Physics, BS",
  "Business Administration and Communication Studies, BS",
  "Business Administration and Criminal Justice, BS",
  "Business Administration and Design, BS",
  "Business Administration and Law, BS",
  "Business Administration and Psychology, BS",
  "Business Administration and Public Health, BS",
  "Business Administration, BSBA",
  "Cell and Molecular Biology, BS",
  "Chemical Engineering and Biochemistry, BSChE",
  "Chemical Engineering and Bioengineering, BSChE",
  "Chemical Engineering and Computer Science, BSChE",
  "Chemical Engineering and Data Science, BSChE",
  "Chemical Engineering and Environmental Engineering, BSChE",
  "Chemical Engineering and Physics, BSChE",
  "Chemical Engineering, BSChE",
  "Chemistry, BS",
  "Civil Engineering and Architectural Studies, BSCE",
  "Civil Engineering and Computer Science, BSCE",
  "Civil Engineering, BSCE",
  "Communication Studies and Design, BS",
  "Communication Studies and Sociology, BA",
  "Communication Studies and Speech-Language Pathology and Audiology, BS",
  "Communication Studies and Theatre, BA",
  "Communication Studies, BA",
  "Communication and Media Studies, BA",
  "Computer Engineering and Computer Science, BSCmpE",
  "Computer Engineering and Physics, BSCmpE",
  "Computer Engineering, BSCmpE",
  "Computer Science and Behavioral Neuroscience, BS",
  "Computer Science and Biology, BS",
  "Computer Science and Business Administration, BS",
  "Computer Science and Cognitive Psychology, BS",
  "Computer Science and Communication Studies, BS",
  "Computer Science and Criminal Justice, BS",
  "Computer Science and Design, BS",
  "Computer Science and Economics, BS",
  "Computer Science and English, BS",
  "Computer Science and Environmental and Sustainability Sciences, BS",
  "Computer Science and Game Development, BS",
  "Computer Science and History, BS",
  "Computer Science and Journalism, BS",
  "Computer Science and Linguistics, BS",
  "Computer Science and Mathematics, BS",
  "Computer Science and Media Arts, BS",
  "Computer Science and Music with Concentration in Music Technology, BS",
  "Computer Science and Music, BS",
  "Computer Science and Philosophy, BS",
  "Computer Science and Physics, BS",
  "Computer Science and Political Science, BS",
  "Computer Science and Politics, Philosophy, and Economics, BS",
  "Computer Science and Sociology, BS",
  "Computer Science and Speech-Language Pathology and Audiology, BS",
  "Computer Science and Theatre, BS",
  "Computer Science, BACS",
  "Computer Science, BSCS",
  "Computing and Law, BS",
  "Criminal Justice and Journalism, BS",
  "Criminal Justice and Philosophy, BS",
  "Criminal Justice and Political Science, BS",
  "Criminal Justice and Psychology, BS",
  "Criminal Justice and Sociology, BS",
  "Criminology and Criminal Justice, BS",
  "Cultural Anthropology and Philosophy, BA",
  "Cultural Anthropology and Religious Studies, BA",
  "Cultural Anthropology and Theatre, BA",
  "Cultural Anthropology, BA",
  "Cultural Anthropology, BS",
  "Cybersecurity and Business Administration, BS",
  "Cybersecurity and Criminal Justice, BS",
  "Cybersecurity and Economics, BS",
  "Cybersecurity, BS",
  "Data Science and Behavioral Neuroscience, BS",
  "Data Science and Biochemistry, BS",
  "Data Science and Biology, BS",
  "Data Science and Business Administration, BS",
  "Data Science and Chemistry, BS",
  "Data Science and Criminal Justice, BS",
  "Data Science and Design, BS",
  "Data Science and Ecology and Evolutionary Biology, BS",
  "Data Science and Economics, BS",
  "Data Science and Environmental and Sustainability Sciences, BS",
  "Data Science and Health Science, BS",
  "Data Science and International Affairs, BS",
  "Data Science and Journalism, BS",
  "Data Science and Linguistics, BS",
  "Data Science and Mathematics, BS",
  "Data Science and Philosophy, BS",
  "Data Science and Physics, BS",
  "Data Science and Psychology, BS",
  "Data Science and Public Health, BS",
  "Data Science and Speech-Language Pathology and Audiology, BS",
  "Data Science, BS",
  "Design and Mathematics, BS",
  "Design and Theatre, BS",
  "Design, BFA",
  "Ecology and Evolutionary Biology, BS",
  "Economics and Business Administration, BS",
  "Economics and Human Services, BS",
  "Economics and Journalism, BS",
  "Economics and Mathematics, BS",
  "Economics and Philosophy, BS",
  "Economics and Psychology, BS",
  "Economics, BA",
  "Economics, BS",
  "Electrical Engineering and Music with Concentration in Music Technology, BSEE",
  "Electrical Engineering and Physics, BSEE",
  "Electrical Engineering, BSEE",
  "Electrical and Computer Engineering, BSCmpE",
  "Electrical and Computer Engineering, BSEE",
  "English and Communication Studies, BA",
  "English and Criminal Justice, BA",
  "English and Cultural Anthropology, BA",
  "English and Design, BA",
  "English and Graphic and Information Design, BA",
  "English and Philosophy, BA",
  "English and Theatre, BA",
  "English, BA",
  "Environmental Engineering and Chemical Engineering, BSEnvE",
  "Environmental Engineering and Data Science, BSEnvE",
  "Environmental Engineering and Health Science, BSEnvE",
  "Environmental Engineering and Landscape Architecture, BSEnvE",
  "Environmental Engineering, BSEnvE",
  "Environmental Studies and History, BA",
  "Environmental Studies and International Affairs, BA",
  "Environmental Studies and Philosophy, BA",
  "Environmental Studies and Political Science, BA",
  "Environmental Studies, BA",
  "Environmental and Sustainability Sciences and Chemistry, BS",
  "Environmental and Sustainability Sciences and Economics, BS",
  "Environmental and Sustainability Sciences and Landscape Architecture, BS",
  "Environmental and Sustainability Sciences, BS",
  "Game Art and Animation, BFA",
  "Game Design and Music with Concentration in Music Technology, BS",
  "Game Design, BFA",
  "Global Asian Studies, BA",
  "Graphic and Information Design and Mathematics, BS",
  "Health Humanities and Health Science, BS",
  "Health Humanities and Public Health, BA",
  "Health Science and Business Administration, BS",
  "Health Science and Communication Studies, BS",
  "Health Science and Law, BS",
  "Health Science and Psychology, BS",
  "Health Science and Sociology, BS",
  "Health Science and Spanish, BS",
  "Health Science, BS",
  "History and Asian Studies, BA",
  "History and Criminal Justice, BA",
  "History and Cultural Anthropology, BA",
  "History and Economics, BA",
  "History and Economics, BS",
  "History and English, BA",
  "History and Philosophy, BA",
  "History and Political Science, BA",
  "History and Religious Studies, BA",
  "History, BA",
  "History, BS",
  "Human Services and Communication Studies, BA",
  "Human Services and Criminal Justice, BS",
  "Human Services and International Affairs, BA",
  "Human Services and Psychology, BS",
  "Human Services and Sociology, BA",
  "Human Services, BA",
  "Human Services, BS",
  "Industrial Engineering and Business Administration, BSIE",
  "Industrial Engineering and Computer Science, BSIE",
  "Industrial Engineering, BSIE",
  "Interdisciplinary Studies, BS",
  "International Affairs and Criminal Justice, BA",
  "International Affairs and Cultural Anthropology, BA",
  "International Affairs and Economics, BA",
  "International Affairs and History, BA",
  "International Affairs and Religious Studies, BA",
  "International Affairs, BA",
  "International Business, BSIB",
  "Jewish Studies and Religion, BA",
  "Journalism and Communication Studies, BA",
  "Journalism and Cultural Anthropology, BA",
  "Journalism and Design, BS",
  "Journalism and English, BA",
  "Journalism and Interaction Design, BS",
  "Journalism and International Affairs, BA",
  "Journalism and Political Science, BA",
  "Journalism and Sociology, BA",
  "Journalism, BA",
  "Landscape Architecture, BLA",
  "Linguistics and Communication Studies, BA",
  "Linguistics and Cultural Anthropology, BS",
  "Linguistics and English, BA",
  "Linguistics and Psychology, BS",
  "Linguistics and Speech-Language Pathology and Audiology, BS",
  "Linguistics, BS",
  "Marine Biology, BS",
  "Marine Biology, BS with Three Seas",
  "Mathematics and Business Administration, BS",
  "Mathematics and Philosophy, BS",
  "Mathematics and Physics, BS",
  "Mathematics and Political Science, BS",
  "Mathematics and Psychology, BS",
  "Mathematics and Sociology, BS",
  "Mathematics, BA",
  "Mathematics, BS",
  "Mechanical Engineering and Bioengineering, BSME",
  "Mechanical Engineering and Computer Science, BSME",
  "Mechanical Engineering and Design, BSME",
  "Mechanical Engineering and History, BSME",
  "Mechanical Engineering and Physics, BSME",
  "Mechanical Engineering, BSME",
  "Media Arts and Communication Studies, BA",
  "Media Arts, BFA",
  "Media and Screen Studies and English, BA",
  "Media and Screen Studies and History, BA",
  "Media and Screen Studies and Journalism, BA",
  "Media and Screen Studies and Media Arts, BA",
  "Media and Screen Studies and Philosophy, BA",
  "Media and Screen Studies and Political Science, BA",
  "Media and Screen Studies and Sociology, BA",
  "Media and Screen Studies and Theatre, BA",
  "Media and Screen Studies and Theatre, BS",
  "Media and Screen Studies, BA",
  "Music and Communication Studies with Concentration in Music Industry, BS",
  "Music with Concentration in Music Industry, BS",
  "Music with Concentration in Music Technology, BS",
  "Music, BA",
  "Nursing, BSN",
  "Nursing, BSN—Accelerated Program for Second-Degree Students",
  "Nursing, BSN—Transfer Track",
  "Performance and Extended Realities, BS",
  "Pharmaceutical Sciences, BS",
  "Philosophy, BA",
  "Philosophy, BS",
  "Physics and Philosophy, BS",
  "Physics, BS",
  "Political Science and Business Administration, BS",
  "Political Science and Communication Studies, BA",
  "Political Science and Communication Studies, BS",
  "Political Science and Economics, BA",
  "Political Science and Economics, BS",
  "Political Science and Human Services, BA",
  "Political Science and Human Services, BS",
  "Political Science and International Affairs, BA",
  "Political Science and Philosophy, BA",
  "Political Science and Philosophy, BS",
  "Political Science, BA",
  "Political Science, BS",
  "Politics, Philosophy, and Economics and Business Administration, BS",
  "Politics, Philosophy, and Economics, BS",
  "Psychology and Design, BS",
  "Psychology and Music, BS",
  "Psychology and Theatre, BS",
  "Psychology, BS",
  "Public Health and Communication Studies, BA",
  "Public Health and Cultural Anthropology, BA",
  "Public Health and Journalism, BA",
  "Public Health and Law, BA",
  "Public Health and Sociology, BA",
  "Public Health, BA",
  "Public Relations, BA",
  "Religious Studies and Africana Studies, BA",
  "Religious Studies, BA",
  "Sociology and Cultural Anthropology, BA",
  "Sociology and Environmental Studies, BA",
  "Sociology and International Affairs, BA",
  "Sociology and Philosophy, BA",
  "Sociology and Political Science, BA",
  "Sociology and Religious Studies, BA",
  "Sociology, BA",
  "Sociology, BS",
  "Spanish and International Affairs, BA",
  "Spanish and Linguistics, BA",
  "Spanish and Public Health, BA",
  "Spanish, BA",
  "Speech-Language Pathology and Audiology and Behavioral Neuroscience, BS",
  "Speech-Language Pathology and Audiology and Human Services, BS",
  "Speech-Language Pathology and Audiology, BS",
  "Studio Art, BFA",
  "Theatre and Interaction Design, BA",
  "Theatre and Interaction Design, BS",
  "Theatre and Journalism, BA",
  "Theatre, BA",
  "Theatre, BS",
];
