name: Migration

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Migrate
        run: pnpm db:migrate

  migrate-staging:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL_STAGING }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        uses: ./tooling/github/setup
        
      - name: Migrate Staging
        run: pnpm db:migrate
